name: Check examples

on:
  issue_comment:
    types: [created]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: false

jobs:
  run:
    if: github.event.issue.pull_request && startsWith(github.event.comment.body, '/check-examples')
    runs-on: ubuntu-latest
    permissions: write-all
    strategy:
      fail-fast: false
      matrix:
        runner: [ 'node', 'bun' ]

    steps:
      - name: Post starting comment
        uses: marocchino/sticky-pull-request-comment@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          header: "check-examples (${{ matrix.runner }})"
          message: |
            Check Example job is scheduled at ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }} with runner ${{ matrix.runner}}.

            Please wait.

      - name: Get PR info
        uses: actions/github-script@v7
        id: pr-info
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const pr = await github.rest.pulls.get({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: context.issue.number
            });
            return {
              ref: pr.data.head.ref,
              sha: pr.data.head.sha
            };

      - name: Debug PR info
        run: echo 'PR info ${{ steps.pr-info.outputs.result }}'

      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{ fromJSON(steps.pr-info.outputs.result).ref }}

      - uses: oven-sh/setup-bun@v2

      - uses: actions/setup-node@v6
        if: ${{ matrix.runner == 'node' }}
        with:
          node-version: 22.18


      - name: Install dependencies
        run: bun install --frozen-lockfile

      - name: Build
        run: bun run --filter '*' build

      - name: Check build examples
        run: bash scripts/build-and-check-examples.sh ${{ matrix.runner }}

      - name: Check import examples
        run: bash scripts/check-import-examples.sh

      - name: Post success comment
        if: ${{ success() }}
        uses: marocchino/sticky-pull-request-comment@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          header: "check-examples (${{ matrix.runner }})"
          message: |
            Check examples job succeeded with runner ${{ matrix.runner}}.
            Please check ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}.

      - name: Post failure comment
        if: ${{ failure() }}
        uses: marocchino/sticky-pull-request-comment@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          header: "check-examples (${{ matrix.runner }})"
          message: |
            Check examples job failed with runner ${{ matrix.runner}}.
            Please check ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}.
