name: Check generate

on:
  issue_comment:
    types: [created]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: false

jobs:
  run:
    if: github.event.issue.pull_request && startsWith(github.event.comment.body, '/check-generate')
    runs-on: ubuntu-latest
    permissions: write-all

    steps:
      - name: Post starting comment
        uses: marocchino/sticky-pull-request-comment@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          number: ${{ github.event.issue.number }}
          header: "check-generate"
          message: |
            Check Generate job is scheduled at ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}.

            Please wait.

      - name: Delete starting comment
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            await github.rest.issues.deleteComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              comment_id: context.payload.comment.id
            });

      - name: Get PR info
        uses: actions/github-script@v7
        id: pr-info
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const pr = await github.rest.pulls.get({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: context.issue.number
            });
            return {
              ref: pr.data.head.ref,
              sha: pr.data.head.sha
            };

      - name: Debug PR info
        run: echo 'PR info ${{ steps.pr-info.outputs.result }}'

      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: true
          ref: ${{ fromJSON(steps.pr-info.outputs.result).ref }}
      - uses: oven-sh/setup-bun@v2
      - name: Install dependencies
        run: bun install --frozen-lockfile

      - name: Build
        run: bun run --filter '*' build

      - name: Check examples
        working-directory: packages/n8n-kit/
        run: bun generate 

      - name: Post success comment
        if: ${{ success() }}
        uses: marocchino/sticky-pull-request-comment@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          number: ${{ github.event.issue.number }}
          header: "check-generate"
          message: |
            Check generate job completed.
            Please check ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}.

      - name: Post failure comment
        if: ${{ failure() }}
        uses: marocchino/sticky-pull-request-comment@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          number: ${{ github.event.issue.number }}
          header: "check-generate"
          message: |
            Check generate job failed.
            Please check ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}.
